config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :todo_lists, only: [:index, :new, :create, :edit, :update, :show]
root "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
validates :title, presence: true
validates :description, length: { minimum: 5 }
validates :priority, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update]

  def index
    @list = TodoList.all
  end

  def new
    @list = TodoList.new
  end

  def create
    @list = TodoList.new(todo_list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to  @list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @list.update(todo_list_params)
        format.html { redirect_to @list, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def show

  end

  private

  def set_list
    @list = TodoList.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:title, :description, :priority)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :list_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :list_description %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority, id: :list_priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo lists</h1>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Priority</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @list.each do |list| %>
    <tr>
      <td><%= list.title %></td>
      <td><%= list.description %></td>
      <td><%= list.priority %></td>
      <td><%= link_to 'Show', list %></td>
      <td><%= link_to 'Edit', edit_todo_list_path(list) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>



<%= link_to 'New List', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<%= form_for @list, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this @list from being saved:</h2>

      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title %>
  <%= f.text_area :description, size: "60x12" %>
  <%= f.submit "Create" %>
  
   
  
<% end %>

app/views/todo_lists/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>



<%= link_to 'Edit', edit_todo_list_path(@list) %> |
<%= link_to 'Back', todo_lists_path %>